"""first migrations

Revision ID: 33e631f04692
Revises: 
Create Date: 2024-11-12 17:40:03.579029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e631f04692'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traps',
    sa.Column('id_alarm', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('time', sa.Time(), server_default=sa.text('CURRENT_TIME'), nullable=True),
    sa.PrimaryKeyConstraint('id_alarm')
    )
    op.create_table('types',
    sa.Column('id_type', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_type'),
    sa.UniqueConstraint('type_name')
    )

    op.execute("""
    INSERT INTO types ("id_type", "type_name") VALUES (1, 'ALL'),(2, 'PC'),(3, 'ROUTER'),(4, 'Mixto')""")

    op.create_table('agents',
    sa.Column('id_agent', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ag_name', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('ag_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ag_type'], ['types.id_type'], ),
    sa.PrimaryKeyConstraint('id_agent'),
    sa.UniqueConstraint('ag_name'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('default_features',
    sa.Column('id_feature', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fe_name', sa.String(length=100), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_type'], ['types.id_type'], ),
    sa.PrimaryKeyConstraint('id_feature')
    )

    op.execute("""INSERT INTO default_features ("id_feature", "fe_name", "id_type") 
VALUES 
    (100, 'Networktraffic', 1),
    (102, 'NumProccesses', 4),
    (103, 'MemorySize', 4),
    (104, 'MemoryUsed', 4),
    (105, 'CpuUsed', 4),
    (106, 'DiskUsed', 4);""")
    op.create_table('active_default',
    sa.Column('id_active', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('id_feature', sa.Integer(), nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_agent'], ['agents.id_agent'], ),
    sa.ForeignKeyConstraint(['id_feature'], ['default_features.id_feature'], ),
    sa.PrimaryKeyConstraint('id_feature', 'id_agent')
    )
    op.create_table('administered_features',
    sa.Column('id_adminis', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sensor', sa.Integer(), nullable=True),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=100), nullable=False),
    sa.Column('adminis_name', sa.String(length=100), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_agent'], ['agents.id_agent'], ),
    sa.PrimaryKeyConstraint('id_adminis')
    )
    op.create_table('alarms',
    sa.Column('id_alarm', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('id_adminis', sa.Integer(), nullable=True),
    sa.Column('id_sensor', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_adminis'], ['administered_features.id_adminis'], ),
    sa.ForeignKeyConstraint(['id_agent'], ['agents.id_agent'], ),
    sa.PrimaryKeyConstraint('id_alarm')
    )
    op.create_table('history_features',
    sa.Column('id_register', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('id_adminis', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_adminis'], ['administered_features.id_adminis'], ),
    sa.ForeignKeyConstraint(['id_agent'], ['agents.id_agent'], ),
    sa.PrimaryKeyConstraint('id_register')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_features')
    op.drop_table('alarms')
    op.drop_table('administered_features')
    op.drop_table('active_default')
    op.drop_table('default_features')
    op.drop_table('agents')
    op.drop_table('types')
    op.drop_table('traps')
    # ### end Alembic commands ###
